version: "3.7"
services:

  app1:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "9090"
    networks:
      - webapp_network

  app2:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "9090"
    networks:
      - webapp_network

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "80:80"
    networks:
      - webapp_network
    depends_on:
      - app1
      - app2

networks:
  webapp_network: